export interface Prospecto {
  id: string,
  tipoIdentificacion: string,
  identificacion: string,
  nombres: string,
  apellidos: string,
  alias: string,
  celular:string,
  grupoEmpresarial: string,
  empresa: string,
  codigoEmpresa: string,
  area: string,
  departamento: string,
  fechaNacimiento: string,
  genero: string,
  direccion: string,
  latitud: string,
  longitud: string,
  email: string
}
