export const environment = {
  production: true,
  apiAuth: 'https://apiauth.enrolapp.ec/api/v1',
  apiEcommerce: 'https://apiecommerce.enrolapp.ec/api/v1',
  apiEnrolApp: 'https://apienrolapp.enrolapp.ec/api/v1',
  apiEvalCore: 'https://apievalcore.enrolapp.ec/api/v1',
  apiUtils: 'https://apiutils.enrolapp.ec/api/v1',
  apiWorkflow: 'https://apiworkflow.enrolapp.ec/api/v1',
  apiImagenes: 'https://imagenes.enrolapp.ec/',
  tokenName: 'tokenUsr',
  uidSuscriptorName: 'uiti',
  iCargoCkName: 'iccn',
  aliasUsuario: 'alus',
  cargoUsuario:'cgus',
  fotoUsuario:'ftus',
  uidCanalWeb: 'e59d975f-92db-444a-a3ce-a91a3d3622e8',
  otpInternaActivacion: 'oirc',
  codFeaTurno: 'TUR',
  codFeaMarcacion: 'MAR',
  codFeaTransferenciaInformacion: 'TIN',
  codFeaEnrolamiento: 'ENR',
  codFeaSolicitudes: 'SOL',
  codFeaGestionSolicitudes: 'GSL',
  codFeaRegistrarSolicitudPermiso: 'RSP',
  codFeaRegistrarSolicitudJustificacion: 'RSJ',
  codFeaRegistrarSolicitudVacacion: 'RSV',
  codFeaRegistrarSolicitudHorasExtras: 'RSH',
  codFeaControlAsistencia: 'CTA',
  codFeaMantenimiento: 'MNT',
  codFeaTrackingFeature: 'TRF',
  codFeaRegistroMarcacionWeb: 'RMW',
  codFeaRegistroMarcacionFacialWeb: 'RMF',
  codFeaAsistenciasNovedades: 'CAN',
  codFeaMesaDeAyuda: 'MDA',
  apiKeyGoogle: 'AIzaSyBG_mU-48ZKA9ZTjadcrMAdcotodDmKZj8',
  versionWeb: '1.0.0'
};
